apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: my-app
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: my-app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: my-app
    spec:
      containers:
        - env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: broker:29092
          image: docker.io/lauhoyin3a/ebank:latest
          name: my-app
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
