apiVersion: apps/v1
kind: Deployment
metadata:
  name: connect
  namespace: confluent
spec:
  selector:
    matchLabels:
      app: connect
  replicas: 1
  template:
    metadata:
      labels:
        app: connect
    spec:
      containers:
        - name: connect
          image: cnfldemos/cp-server-connect-datagen:0.5.3-7.1.0
          ports:
            - containerPort: 8083
          env:
            - name: CONNECT_BOOTSTRAP_SERVERS
              value: "broker:29092"
            - name: CONNECT_REST_ADVERTISED_HOST_NAME
              value: "connect"
            - name: CONNECT_GROUP_ID
              value: "compose-connect-group"
            - name: CONNECT_CONFIG_STORAGE_TOPIC
              value: "docker-connect-configs"
            - name: CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
              value: "1"
            - name: CONNECT_OFFSET_FLUSH_INTERVAL_MS
              value: "10000"
            - name: CONNECT_OFFSET_STORAGE_TOPIC
              value: "docker-connect-offsets"
            - name: CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
              value: "1"
            - name: CONNECT_STATUS_STORAGE_TOPIC
              value: "docker-connect-status"
            - name: CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
              value: "1"
            - name: CONNECT_PLUGIN_PATH
              value: "/usr/share/java,/usr/share/confluent-hub-components"
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 15
            periodSeconds: 10