
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: my-app
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: my-app
    template:
      metadata:
        labels:
          app: my-app
      spec:
        containers:
          - name: zookeeper
            image: confluentinc/cp-zookeeper:7.4.0
            ports:
              - containerPort: 2181
            readinessProbe:
              tcpSocket:
                port: 2181
              initialDelaySeconds: 5
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
            env:
              - name: ZOOKEEPER_CLIENT_PORT
                value: "2181"
              - name: ZOOKEEPER_TICK_TIME
                value: "2000"
          - name: broker
            image: confluentinc/cp-server:7.4.0
            ports:
              - containerPort: 9092
              - containerPort: 9101
            readinessProbe:
              tcpSocket:
                port: 9092
              initialDelaySeconds: 10
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
            env:
          - name: KAFKA_BROKER_ID
            value: "1"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "zookeeper:2181"
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092"
          - name: KAFKA_METRIC_REPORTERS
            value: "io.confluent.metrics.reporter.ConfluentMetricsReporter"
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            value: "1"
          - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
            value: "0"
          - name: KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR
            value: "1"
          - name: KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR
            value: "1"
          - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
            value: "1"
          - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
            value: "1"
          - name: KAFKA_JMX_PORT
            value: "9101"
          - name: KAFKA_JMX_HOSTNAME
            value: "localhost"
          - name: KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL
            value: "http://schema-registry:8081"
          - name: CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS
            value: "broker:29092"
          - name: CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS
            value: "1"
          - name: CONFLUENT_METRICS_ENABLE
            value: "true"
          - name: CONFLUENT_SUPPORT_CUSTOMER_ID
            value: "anonymous"
          - name: schema-registry
            image: confluentinc/cp-schema-registry:7.4.0
            ports:
              - containerPort: 8081
            readinessProbe:
              httpGet:
                path: /subjects
                port: 8081
              initialDelaySeconds: 10
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
            env:
              - name: SCHEMA_REGISTRY_HOST_NAME
                value: "schema-registry"
              - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
                value: "broker:29092"
              - name: SCHEMA_REGISTRY_LISTENERS
                value: "http://0.0.0.0:8081"
          - name: connect
            image: cnfldemos/cp-server-connect-datagen:0.5.3-7.1.0
            ports:
              - containerPort: 8083
            readinessProbe:
              httpGet:
                path: /connectors
                port: 8083
              initialDelaySeconds: 20
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
            env:
              - name: CONNECT_BOOTSTRAP_SERVERS
                value: "broker:29092"
              - name: CONNECT_REST_ADVERTISED_HOST_NAME
                value: "connect"
              - name: CONNECT_GROUP_ID
                value: "compose-connect-group"
              - name: CONNECT_CONFIG_STORAGE_TOPIC
                value: "docker-connect-configs"
              - name: CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
                value: "1"
              - name: CONNECT_OFFSET_FLUSH_INTERVAL_MS
                value: "10000"
              - name: CONNECT_OFFSET_STORAGE_TOPIC
                value: "docker-connect-offsets"
              - name: CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
                value: "1"
              - name: CONNECT_STATUS_STORAGE_TOPIC
                value: "docker-connect-status"
              - name: CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
                value: "1"
              - name: CONNECT_KEY_CONVERTER
                value: "org.apache.kafka.connect.json.JsonConverter"
              - name: CONNECT_VALUE_CONVERTER
                value: "org.apache.kafka.connect.json.JsonConverter"
              - name: CONNECT_INTERNAL_KEY_CONVERTER
