apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: confluent
spec:
  selector:
    matchLabels:
      app: zookeeper
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.4.0
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  stat /tmp/zookeeper/version-2/* >/dev/null 2>&1
            initialDelaySeconds: 10
            periodSeconds: 30